name: listing, testing
on:
    push:
        branches: [master]
jobs:
    pipeline:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v2
            - name: Staring Node.js ${{matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{matrix.node-version}}
            - name: install modules
              run: npm ci
            - name: linting type script
              run: npm run lint:ts
            - name: linting css
              run: npm run lint:css
            - name: unit testing
              run: npm run unit
