name: listing, testing
on:
    push:
        branches: [master]
jobs:
    pipeline:
        runs-on: ubuntu-18.04
        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v2
            - name: Staring Node.js ${{matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{matrix.node-version}}
            - name: install modules
              run: npm install config set legacy-peer-deps true install --force
            - name: linting type script
              run: npx eslint \"src/**/*.{ts,tsx,jsx,js}\"
            - name: linting css
              run: npx stylelint \"**/*.css\"
            - name: unit testing
              run: jest --config ./jest.config.js
